services:
  - type: web
    name: shieldrelay-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000"
    rootDir: backend
    autoDeploy: true

  - type: static
    name: shieldrelay-frontend
    rootDir: frontend
    buildCommand: "npm install && npm run build"
    staticPublishPath: dist
    autoDeploy: true